comment_width = 100
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
# format_strings = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = false
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
wrap_comments = false
