[package]
name = "serial"
version = "0.1.0"
authors = ["TomSmeets <tom@tsmeets.nl>"]
edition = "2018"
default-run = "sdl"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sdl"
required-features = [ "platform-sdl" ]

[[bin]]
name = "web"
required-features = [ "platform-web" ]


[features]
default = [ "platform-sdl", "platform-gl" ]

platform-web = ["builder-single",                  "stdweb", "stdweb-derive", "base64", "png" ]
platform-sdl = ["builder-threaded", "builder-ocl", "sdl2" ]
platform-gl  = ["builder-threaded", "builder-ocl", "glutin", "gilrs", "memoffset" ]

builder-ocl      = [ "ocl" ]
builder-threaded = []
builder-single   = []

static = [ "sdl2/static-link", "sdl2/bundled" ]

# TODO: it might be time to move away from sdl2
# lets stay away from vulkan for now.
# glium + glutin + gilrs seems to work ok
# better: seperate into library parts that don't depend on any backend
# then implement the backend stuff directly in opengl,vulkan,webgl, etc
[dependencies]
serde      = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1.0" }
cgmath     = { version = "0.17", features = [ "serde" ] }
rand       = { version = "0.7" }
crossbeam-channel = { version = "0.4" }

sdl2          = { version = "0.34", optional = true, features = [ "unsafe_textures" ] }
ocl           = { version = "0.19", optional = true }

stdweb        = { version = "0.4",  optional = true }
stdweb-derive = { version = "0.5",  optional = true }
png           = { version = "0.16", optional = true }
base64        = { version = "0.12", optional = true }
glutin    = { version = "0.24.0", optional = true }
gilrs     = { version = "0.7.4", optional = true }
memoffset = { version = "0.5.4", optional = true }

[build-dependencies]
gl_generator = "0.14.0"

[dev-dependencies]
criterion = "0.3"

[profile.release]
debug = true
