[package]
name = "serial"
version = "0.1.0"
authors = ["TomSmeets <tom@tsmeets.nl>"]
edition = "2018"
default-run = "sdl"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sdl"
required-features = [ "platform-sdl" ]

[[bin]]
name = "web"
required-features = [ "platform-web" ]


[features]
default = [ "platform-sdl" ]

platform-web = [ "stdweb", "stdweb-derive", "builder-single", "base64", "image" ]
platform-sdl = [ "sdl2", "builder-threaded", "builder-ocl" ]

builder-ocl = [ "ocl" ]
builder-threaded = []
builder-single = []

static = [ "sdl2/static-link", "sdl2/bundled" ]

# TODO: it might be time to move away from sdl2
# lets stay away from vulkan for now.
# glium + glutin + gilrs seems to work ok
# better: seperate into library parts that don't depend on any backend
# then implement the backend stuff directly in opengl,vulkan,webgl, etc
[dependencies]
serde      = { version =  "1.0", features = [ "derive", "rc" ] }
serde_json = "1.0"
cgmath     = { version = "0.17", features = [ "serde" ] }
rand       = "0.7"
rusttype   = "0.8"

image         = { version = "0.23", optional = true }
base64        = { version = "0.12", optional = true }
sdl2          = { version = "0.33", optional = true, features = [ "unsafe_textures" ] }
ocl           = { version = "0.19", optional = true }
stdweb        = { version = "0.4",  optional = true }
stdweb-derive = { version = "0.5",  optional = true }

[dev-dependencies]
criterion = "0.3"

[profile.release]
debug = true
