[package]
name = "fractal-toy"
version = "0.1.0"
authors = ["Tom Smeets <tom.tsmeets@gmail.com>"]
edition = "2018"
license = "GPL-v2"

[dependencies]
bytemuck = "1.5.1"
cgmath = "0.18.0"
naga = "0.4.1"
pollster = "0.2.4"
serde = { version = "1.0.126", features = [ "derive" ] }
structopt = "0.3.21"
wgpu = "0.8.1"
winit = "0.25.0"
