newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true

# These are unstable, but i like them
overflow_delimited_expr = true
match_block_trailing_comma = true
