[package]
name = "minimal"
version = "0.1.0"
authors = ["TomSmeets <tom@tsmeets.nl>"]
edition = "2018"

[features]
static = [ "sdl2/static-link", "sdl2/bundled" ]

[dependencies]
sdl2 = { version = "0.33" }

[profile.release]
lto = "fat"
panic = "abort"
